import { LetterT } from "@/app/types/ApiRes";
export function createEmailTemplate(letterData: LetterT): string {
    return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; }
            .header { background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
            .content { margin-bottom: 20px; }
            .footer { font-size: 12px; color: #666; border-top: 1px solid #eee; padding-top: 15px; }
            .highlight { background-color: #e3f2fd; padding: 10px; border-radius: 3px; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h2>Leave Application Received</h2>
                <p><strong>From:</strong> ${letterData.from.name} (${letterData.from.usn})</p>
            </div>
            
            <div class="content">
                <p>Dear ${letterData.to.name},</p>
                
                <p>You have received a leave application from <strong>${letterData.from.name}</strong> (USN: ${letterData.from.usn}).</p>
                
                <div class="highlight">
                    <p><strong>Subject:</strong> ${letterData.subject}</p>
                    <p><strong>Date:</strong> ${letterData.date}</p>
                </div>
                
                <p><strong>Please find the complete leave letter attached as a PDF document for your review and consideration.</strong></p>
                
                <p>For any queries or clarifications regarding this application, you may contact the student directly at: 
                   <a href="mailto:${letterData.from.email}">${letterData.from.email}</a></p>
            </div>
            
            <div class="footer">
                <p>This email was automatically generated by the Academic Management System.</p>
                <p><strong>Acharya Institute of Technology</strong><br>
                   Soldevanahalli, Acharya Dr. Sarvepalli Radhakrishnan Road<br>
                   Bangalore - 560107, Karnataka, India</p>
            </div>
        </div>
    </body>
    </html>`;
}